GET http://127.0.0.1:8000/api/post HTTP/1.1

###

POST http://127.0.0.1:8000/api/post HTTP/1.1
Content-Type: application/json

{
    "username": "user6",
    "password": "pass6",
    "password_confirmation": "pass6",
    "email": "email6"
}
###
GET http://127.0.0.1:8000/api/post/login
Content-Type: application/application/json

{
    "username": "user6",
    "password": "pass6"
}

###
